### ISSUE TITLE
How to update story content dynamically

### ISSUE THREAD

**Issue by strmchsr** [ertgrulll/advstory#14]
I want to update item count dynamically (by pagination or infinite scrolling)

I did the that in tray view by adding a scrollcontroller, But to update the story view we need some way to update the story item when data updates via pagination,

**Comment by ertgrulll** [comment]
Hello, _AdvStory_ allows `async` `storyBuilder` function to requesting data from server. Runs `storyBuilder` and keeps result in the memory. To update story content count, `storyBuilder` function should be updated and previously built stories should be cleared, which is not expected behaviour in many use cases. You need to know total story count before creating story view in current implementation, you can paginate stories in `storyBuilder` but not contents or trays. I designed _AdvStory_ to use with previosuly fetched tray data, i'm requesting user story when a tray tapped or story swiped. But If you provide some code or better yet a reproducible repository I can try more help.

**Comment by strmchsr** [comment]
Hi @ertgrulll thanks for the quick response, 
 I did the pagination in tray, following is the PR:
[PR](https://github.com/strmchsr/advstory/pull/3/files).
Now the problem is:
- initially the api called and 10 data loaded in tray.
- Now I tap on 2nd item in the tray(each story has only one item)
- Now when story reaches to 7th , I call the data for next page and not the count(tray count) is 20
- Although tray gets updated but story view is closed after 10th

**Comment by ertgrulll** [comment]
0.2.0 version published, I have made changes to allow `storyCount` update.  This version should fix your problem, you can paginate stories now. If you see any other problem, please file a new issue. Happy codings!

**Comment by strmchsr** [comment]
Thanks ! It was quick
