### ISSUE TITLE
AdvStoryController throws exception when jumpTo called on trayTap event

### ISSUE THREAD

**Issue by itsjanjan** [ertgrulll/advstory#15]
How can I implement seen feature like when I already saw the content It will jump to next content which not yet viewed?

Currently, when the tray open I can't skip or jump it using the controller listener.

**Comment by itsjanjan** [comment]
How can I implement seen feature like when I already saw the content It will jump to next content which not yet viewed?

**Comment by ertgrulll** [comment]
I am able to reproduce the issue. When "jumpTo" is called on the `StoryEvent.trayTap`, `AdvStoryController` throws an exception because the story view page controller has not been created yet. I will release a new version to fix the issue as soon as possible.

**Comment by itsjanjan** [comment]
Cool, Thank you for your awesome package.

**Comment by ertgrulll** [comment]
`jumpTo` bug fixed in version 0.2.0, but I have added interceptor support to make things better. When you call `jumpTo` on `StoryEvent.trayTap`, AdvStory creates tapped story and some of it's content and after that jumps to the given position, but using interceptor you can change opening position before view opened. 

I didn't update docs yet, but you can look at [interceptor example](https://github.com/ertgrulll/advstory/blob/master/example/lib/examples/interceptor.dart) to see usage. Use `setTrayTapInterceptor`. from controller,  `AdvStory` calls this method when `StoryEvent.trayTap` happened return desired `StoryPosition` to open view at that position when needed, or return null to allow to continue default flow.

Also you can add interceptor to block any other story event, not just for tray tap. Happy coding!
